<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="85" started-at="2017-01-18T06:31:30Z" finished-at="2017-01-18T06:31:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="85" started-at="2017-01-18T06:31:30Z" finished-at="2017-01-18T06:31:30Z">
      <class name="App_modules.MD04_Draw_Flow">
        <test-method status="FAIL" signature="forallUsers()[pri:0, instance:App_modules.MD04_Draw_Flow@78e117e3]" name="forallUsers" is-config="true" duration-ms="0" started-at="2017-01-18T12:01:30Z" finished-at="2017-01-18T12:01:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at App_modules.MD04_Draw_Flow.forallUsers(MD04_Draw_Flow.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.TestRunner.beforeRun(TestRunner.java:631)
	at org.testng.TestRunner.run(TestRunner.java:599)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forallUsers -->
        <test-method status="SKIP" signature="Signin_success()[pri:0, instance:App_modules.MD04_Draw_Flow@78e117e3]" name="Signin_success" duration-ms="1" started-at="2017-01-18T12:01:30Z" finished-at="2017-01-18T12:01:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signin_success -->
        <test-method status="SKIP" signature="setUp()[pri:0, instance:App_modules.MD04_Draw_Flow@78e117e3]" name="setUp" duration-ms="2" started-at="2017-01-18T12:01:30Z" finished-at="2017-01-18T12:01:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="teardown()[pri:0, instance:App_modules.MD04_Draw_Flow@78e117e3]" name="teardown" is-config="true" duration-ms="0" started-at="2017-01-18T12:01:30Z" finished-at="2017-01-18T12:01:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- App_modules.MD04_Draw_Flow -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
